# similarity model
# must match model_name used for model instantiation in factory.py
# implemented models: mcft, siamese-style, VGGish-embedding
model_name: VGGish-embedding

# model weight filename relative to the model/weight directory
# can be any non-empty string for mcft
model_filepath: vggish_pretrained_convs.pth

# dataset of audio files to be queried relative to the data directory
# must match dataset_name used for dataset instantiation in factory.py
# must match the name of the directory containing the audio files
# implemented datasets: test_dataset, otomobile
dataset_name: test_dataset

# directory for storing preprocessed or embedded data relative to the data
# directory
representation_directory: representations

# batch size of audio representation construction
construct_representation_batch_size:

# batch size of similarity inference
measure_similarity_batch_size:

# Toggle whether search results must match the user-specified text
require_text_match: false
